# Generated by Django 2.2.16 on 2023-05-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20230506_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/posts/', verbose_name='Картинка'),
        ),
    ]
